# Generated by Django 5.0.1 on 2025-10-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0004_serviceenquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceEnquiry',
        ),
    ]
